// Generated by CoffeeScript 1.9.3
(function() {
  var json, jsondsl;

  jsondsl = require('./../index.js').parse;

  json = {
    div: 'foo'
  };

  console.log(JSON.stringify(json, null, 2));

  console.log(jsondsl(json));

  if (jsondsl(json !== "<div>foo</div>")) {
    process.exit(1);
  }

  json = {
    div: {
      div: {
        div: 'foo'
      }
    }
  };

  console.log(JSON.stringify(json, null, 2));

  console.log(jsondsl(json));

  if (jsondsl(json !== "<div><div><div>foo</div></div></div>")) {
    process.exit(1);
  }

  json = {
    foo: 'bar',
    div: {
      span: {
        div: 'foo'
      }
    }
  };

  console.log(JSON.stringify(json, null, 2));

  console.log(jsondsl(json));

  if (jsondsl(json !== "<foo>bar</foo><div><span><div>foo</div></span></div>")) {
    process.exit(1);
  }

  json = {
    div: {
      div: {
        div: 'foo'
      }
    }
  };

  jsondsl = require('./../index.js');

  jsondsl.parseKey = function(k) {
    return k + "[%s]";
  };

  console.log(jsondsl.parse(json));

  if (jsondsl.parse(json !== "div[div[div[foo]]]")) {
    process.exit(1);
  }

  console.log("tests ok");

}).call(this);
