// Generated by CoffeeScript 1.9.3
(function() {
  var data, dsl, json, zen;

  dsl = require('./../index.js');

  zen = require('zen-coding');

  dsl.parseKey = function(k) {
    return zen(k + '>{%s}');
  };

  dsl.parseValue = function(v, data) {
    return data[v];
  };

  json = {
    'div#foo.flop>fieldset>div>ul': {
      'li.one>a[href="/"]': 'one',
      'li.two>a[href="/"]': 'two'
    }
  };

  data = {
    'one': 'hello',
    'two': 'world'
  };

  console.log(JSON.stringify(json, null, 2));

  console.log(dsl.parse(json, data));

}).call(this);
