// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = (function() {
    return {
      opts: {
        token: "%s"
      },
      parseKey: function(k) {
        return "<" + k + ">%s</" + k + ">";
      },
      parseValue: function(v, d) {
        return v;
      },
      parseDSL: function(json, data, str) {
        var k, nk, nv, v;
        if (str == null) {
          str = '';
        }
        if (typeof json === "object") {
          for (k in json) {
            v = json[k];
            nk = this.parseKey(k);
            nv = this.parse(v, data, '');
            str += nk.replace(/%s/, nv);
          }
        }
        if (typeof json === "string") {
          str += this.parseValue(json, data);
        }
        if (str == null) {
          return json;
        } else {
          return str;
        }
      },
      parse: function(json, data) {
        return this.parseDSL(json, data);
      }
    };
  })();

}).call(this);
